name: "Dioxus Android Build"
description: "Build your Android apps with Dioxus"

runs:
  using: "composite"
  steps:
    - name: "Add Android targets"
      run: "rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android"
    - name: "Install Java"
      run: "apt install default-jre && java -version"
    - name: "Download and install Android SDK manager"
      run: "wget https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip && unzip https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip"
